// import SignIn from "../components/Authentication/SignIn";
import HomePage from "../components/HomePageComponent/HomePage";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div>
      <HomePage />
      {}

      {children}
    </div>
  );
}
